enum ActionKeywordEnum {
  STOP_SEARCH_MODE = 'STOP_SEARCH_MODE',
  SHOW_LOADING = 'SHOW_LOADING',
  FETCH_PREDICTION = 'FETCH_PREDICTION',
  SAVE_AUTOCOMPLETE = 'SAVE_AUTOCOMPLETE',
}
export default ActionKeywordEnum;
